# Generated by Django 3.0.2 on 2020-04-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_auto_20200408_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='fullName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='firstName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='lastName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
