# Generated by Django 3.0.2 on 2020-04-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_auto_20200416_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='lattiude',
            new_name='latitude',
        ),
    ]
