# Generated by Django 3.0.2 on 2020-04-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0005_auto_20200417_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='primary_care_trust',
            field=models.CharField(default='', max_length=100),
        ),
    ]
