# Generated by Django 3.0.2 on 2020-04-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0006_nurse_primary_care_trust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='firstName',
            field=models.CharField(default='', max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='lastName',
            field=models.CharField(default='', max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phoneNumber',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='postCode',
            field=models.CharField(default='', max_length=10, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='primary_care_trust',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdffile', models.FileField(blank=True, null=True, upload_to='')),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nurse.Nurse')),
            ],
        ),
    ]
