# Generated by Django 3.0.2 on 2020-04-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0007_auto_20200417_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='addressLine1',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='nurse',
            name='addressLine2',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
