# Generated by Django 3.0.2 on 2020-04-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0008_auto_20200417_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='districtNurseBorough',
            field=models.CharField(default='', max_length=100, verbose_name='District Nursing Borough'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='teamName',
            field=models.CharField(default='', max_length=100, verbose_name='Team Name'),
        ),
    ]
