# Generated by Django 3.0.2 on 2020-02-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nurse',
        ),
    ]
